.circleci/config.yml
.gitignore
LICENSE
README.md
astronomer/airflow/version_check/models.py
astronomer/airflow/version_check/plugin.py
astronomer/airflow/version_check/static/update-notice.css
astronomer/airflow/version_check/static/update-notice.js
astronomer/airflow/version_check/templates/astro-baselayout.html
astronomer/airflow/version_check/templates/update-available.html
astronomer/airflow/version_check/update_checks.py
dev-requirements.txt
pyproject.toml
setup.cfg
setup.py
tests/conftest.py
tests/test_plugin.py

This plugin operates as follows:
- It uses `functools.wraps` to "hook" in to various places in Airflow
that don't have pre-existing hook points.
This does mean that if those function names change in the future this
will stop working.
- It runs a thread in the scheduler process to make requests to the
update server.
It hooks in to airflow.jobs.scheduler_job.SchedulerJob._execute_helper
to start the thread.
- Available updates are stored in the database for the UI to query
- The UI display is done by customizing the `appbuilder.base_template`,
as again, there aren't enough hook points to inject our front end code
any other way. This needs AIRFLOW-6733 and AIRFLOW-6734 to work.
- This notice is shown for all (logged in) users, but the dismiss button is
only visible for admins.
- There aren't …

v1 of the plugin

---

.circleci/config.yml
dev-requirements.txt
setup.py

This uses a new helper repo I created https://github.com/astronomer/pip-release-utilities -- as we have three or so modules deploying to there and we want to share some of the deploy steps.

Automatically deploy tagged releases to bucket

---

dev-requirements.txt

To work on 1.10.7 we need our fork/back-ported fixes.
The old way of installing didn't work since we made our pip repo behave more like a proper one.

Fix installing of AC in our tests

---

astronomer/airflow/version_check/update_checks.py
dev-requirements.txt
setup.py

The update check is for AC, not Airflow, so it makes sense that we epend upon it

Require astronomer-certified

---

astronomer/airflow/version_check/plugin.py
astronomer/airflow/version_check/update_checks.py

This makes it easier for us to install in older versions of our platform
without it breaking things. (Due to other limitations we haven't been
running migrations from the user image, but the stock/default image
which likely won't have this plugin installed.)

Don't error if update check tables don't exist.

---

astronomer/airflow/version_check/models.py
astronomer/airflow/version_check/plugin.py

Without doing this we will show
> ERROR: duplicate key value violates unique constraint "astro_version_check_pkey"
in the Postgres server logs -- nothing is wrong with this, but it isn't
great to show errors, especially in local environments where users might notice this.
(We still need the try/except around the bulk save as two processes
could race to create it still.)

Select if unique constraint row exists

---

astronomer/airflow/version_check/models.py
astronomer/airflow/version_check/plugin.py
astronomer/airflow/version_check/update_checks.py

depends on https://github.com/astronomer/astronomer-airflow-version-check/pull/13
(not https://github.com/astronomer/astronomer-airflow-version-check/pull/13 is enough to fix https://github.com/astronomer/issues/issues/1561)
I have tested this locally and on staging.

Set hidden_from_ui=True for Old Versions

---

astronomer/airflow/version_check/models.py
astronomer/airflow/version_check/plugin.py

It seems like mysql doesn't like unbounded character text types as a primary key. For mysql/maria table creation fails with the following:
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1170, "BLOB/TEXT column 'version' used in key specification without a key length")
[SQL:
CREATE TABLE astro_available_version (
version TEXT NOT NULL,
level TEXT NOT NULL,
date_released DATETIME NOT NULL,
description TEXT,
url TEXT,
hidden_from_ui BOOL NOT NULL,
PRIMARY KEY (version),
CHECK (hidden_from_ui IN (0, 1))
)
Per this post: https://stackoverflow.com/questions/1827063/mysql-error-key-specification-without-a-key-length
I updated the primary key type from an unbounded text type to String(255) which fixes the issue.

Updated text type of primary key for version table

---

astronomer/airflow/version_check/update_checks.py
setup.py

With this change:
```
185.80.118.24 - "GET https://updates.astronomer.io/astronomer-certified?site=http%3A%2F%2Flocalhost%3A8080" 200 3051 "airflow/1.10.10.post3 {"airflow_configs":{"executor":"LocalExecutor","store_serialized_dags":"False"},"ci":null,"cpu":"x86_64","distro":{"name":"Alpine Linux","version":"3.10.5"},"implementation":{"name":"CPython"},"python":"3.7.7","system":{"name":"Linux","release":"4.19.76-linuxkit"}}"
```

Add more data to UserAgent on Updater Service requests

---

astronomer/airflow/version_check/plugin.py

Fixes the following error:
```
scheduler_1 | [2020-10-14 15:53:58,711] {plugins_manager.py:155} ERROR - Failed to import plugin astronomer_version_check
scheduler_1 | Traceback (most recent call last):
scheduler_1 |   File "/usr/local/lib/python3.7/site-packages/airflow/plugins_manager.py", line 152, in load_entrypoint_plugins
scheduler_1 |     plugin_instance.on_load()
scheduler_1 |   File "/usr/local/lib/python3.7/site-packages/astronomer/airflow/version_check/plugin.py", line 38, in on_load
scheduler_1 |     cls.add_before_call(airflow.jobs.scheduler_job.SchedulerJob, '_execute_helper', cls.start_update_thread)
scheduler_1 |   File "/usr/local/lib/python3.7/site-packages/astronomer/airflow/version_check/plugin.py", line 21, in add_before_call
scheduler_1 |     fn = getattr(mod_or_cls, …
```

Make the version check plugin Airflow 2.0 compatible

---

dev-requirements.txt

Without this the tests fails with since Airflow need ~=19.3:
```
[2020-10-15 14:36:35,754] {plugins_manager.py:111} ERROR - Failed to import plugin astronomer_version_check
Traceback (most recent call last):
File "/home/circleci/project/.venv/lib/python3.7/site-packages/airflow/plugins_manager.py", line 105, in load_entrypoint_plugins
plugin_obj = entry_point.load()
File "/home/circleci/project/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2461, in load
self.require(*args, **kwargs)
File "/home/circleci/project/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2484, in require
items = working_set.resolve(reqs, env, installer, extras=self.extras)
File "/home/circleci/project/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 792, in …
```

Pin attrs to less than 20.0

---

astronomer/airflow/version_check/update_checks.py
dev-requirements.txt

Because `self.check_interval` was a timedelta object, check with 0 resulted in False.
```
In [1]: from datetime import timedelta
In [2]: timedelta(seconds=0)
Out[2]: datetime.timedelta(0)
In [3]: timedelta(seconds=0) == 0
Out[3]: False
```

Fix disabling update_check_interval checks

---

astronomer/airflow/version_check/update_checks.py

Before 2.0 the `app.appbuilder.base_template` was `airflow/master.html`. From 2.0 it is called `airflow/main.html`

Replace 2.0 Appbuilder base template

---

astronomer/airflow/version_check/update_checks.py

`appbuilder.add_api` has been removed in airflow. Luckily, it's
a wrapper around `appbuilder.add_view_no_menu`
Airflow PR: https://github.com/apache/airflow/pull/20487
Closes: https://github.com/astronomer/issues-airflow/issues/153

Use add_view_no_menu since add_api is removed in airflow

---

CHANGELOG.md
astronomer/airflow/version_check/plugin.py

Released 2022-01-24
- Use `add_view_no_menu since add_api` is removed in airflow (#24)
- Fix CI issues and Bump dev requirements (#26)

Version 1.0.8

---

.circleci/config.yml
astronomer/airflow/version_check/update_checks.py
pyproject.toml
setup.py

- Bumps docker image from ` circleci/python:3.7-buster` to `cimg/python:3.7` (https://circleci.com/developer/images/image/cimg/python)
- Replaces deprecated log.warn() with log.warning
- Bump setuptools in pyproject.toml

Bump CI dependencies

---

astronomer/airflow/version_check/update_checks.py
tests/conftest.py
tests/test_update_checks.py

This PR improves how we display available updates. If a user has image 2.2.1-2 and
there're releases 2.2.1-3 and 2.2.3-4, we want to show 2.2.1-3 to the user. Until the user
upgrades to 2.2.1-3 he cannot see 2.2.3-4.
closes https://github.com/astronomer/issues-airflow/issues/154

Show available updates in a better way

---

CHANGELOG.md
astronomer/airflow/version_check/plugin.py

- Show available updates in a better way (#34)
- Add pre-commit (#35)
- Repeat 'venv' creation in publish job (#32)
- Fix setuptools not found during publish (#31)
- Bump CI dependencies (#28)

Version 1.0.9

---

.gitignore
.pre-commit-config.yaml
astronomer/airflow/version_check/update_checks.py
dev-requirements.txt
setup.py
tests/conftest.py

The register method of Blueprint changed in Flask 2+ which Airflow
2.3.3 is based on. This PR fixes the issue and also removed astronomer-certified
as dependency of this plugin.
Furthermore, a distro warning was also fixed

Fix plugin to work with Airflow 2.3.3+

---

.gitignore
astronomer/airflow/version_check/plugin.py
astronomer/airflow/version_check/update_checks.py
pyproject.toml
tests/conftest.py
tests/test_plugin.py
tests/test_update_checks.py

We currently depend on a before call hook on `upgradedb` to create tables
for the plugin. This PR replaces it with a query for existence of the plugin
tables and creates the table if needed.
Also, some deprecation warnings were fixed

Remove create table hook on `upgradedb`

---

astronomer/airflow/version_check/templates/update-available.html
astronomer/airflow/version_check/update_checks.py
tests/conftest.py
tests/test_runtime_update_checks.py

This PR adapts this plugin to work in astronomer runtime.
Leveraging the ASTRONOMER_RUNTIME_VERSION environment variable, we can
tell if we are on runtime or not and apply the logic accordingly

Make version check plugin work in runtime

---

astronomer/airflow/version_check/plugin.py

This contains fixes to make the version check plugin work in 2.4.0 as well as in runtime

Release v1.0.11

---

.circleci/config.yml

Instead of installing a bunch of binary packages so pip can successfully install the cryptography C shims, this PR minimizes the number of installed packages, and pre-installs `wheel` into the virtualenv so that pip can use the wheel packages of cryptography.
I manually tested the `verify tag` commands on bare metal macOS as well as within a Docker container.
Using wheel packages is likely going make our build and deploy process slightly more resilient than installing binary packages and compiling cryptography each time (as the Docker image may get updated out from under us and binary package names may change around).

Manually pre-install wheel so cryptography gets installed from a wheel

---

astronomer/airflow/version_check/update_checks.py
tests/test_runtime_update_checks.py
tests/test_update_checks.py

When requests.get fails with the above exceptions, we should catch it and avoid crashing the scheduler
related: https://github.com/astronomer/issues/issues/5140

Catch SSLError & HTTPError during requests.get

---

astronomer/airflow/version_check/update_checks.py

Since runtime 6.1.0, the update available notice was not shown. What I was able to find was that the base template comes as runtime_base.html, updating it here made it to work

Update the base template options

---

astronomer/airflow/version_check/plugin.py

Bumping this to 2.0.0 since we dropped AC support.

Releasing 2.0.0

---

.circleci/config.yml
astronomer/airflow/version_check/models.py
dev-requirements.txt
tests/test_runtime_update_checks.py

This was using session to check dialect and thus interferring with scheduler session
but sqlalchemy has with_variant method for doing the same thing

Properly set the version column type

---

README.md
astronomer/airflow/version_check/models.py
astronomer/airflow/version_check/plugin.py
astronomer/airflow/version_check/templates/update-available.html
astronomer/airflow/version_check/update_checks.py
dev-requirements.txt
tests/test_runtime_update_checks.py

This PR adds functionality to display a warning in the Airflow UI when the current runtime version has been yanked. This also adds a `yanked` column to the `AstronomerAvailableVersion` model to store the yanked status. When looking for possible upgrades, if it's yanked, we don't show it to the user. For example, if the user is on version 10.6 and version 10.7 has been yanked, we do not show 10.7 as an available upgrade.
I have tested the change by manually changing the version as yanked in the database:
I have tested it on the following Astro deployment
This pull request depends on the following pull request being merged first:
- [PR #72](https://github.com/astronomer/astronomer-airflow-version-check/pull/72)
closes: #68

Add Warning for Yanked Runtime Versions

---

.pre-commit-config.yaml
astronomer/airflow/version_check/models.py
astronomer/airflow/version_check/update_checks.py

This updates the hooks, but also:
- switches to the hook from the official shellcheck repo
- bumps the min python version to 3.8 for pyupgrade

Update pre-commit hooks

---

.circleci/config.yml
CHANGELOG.md
astronomer/airflow/version_check/models.py
astronomer/airflow/version_check/plugin.py
astronomer/airflow/version_check/update_checks.py
dev-requirements.txt
pyproject.toml
tests/test_runtime_update_checks.py

Make the version check plugin compatible with the new RT version scheme, 
example 2.9-4-python-3.9 / 3.0-1-nightly20241216
Closes: https://github.com/astronomer/astro-runtime/issues/2020
Slack discussion: https://astronomer.slack.com/archives/C01UJJEN0P3/p1740998091410679

Fix version check plugin for the new version scheme

---

CHANGELOG.md
astronomer/airflow/version_check/plugin.py

- Use new versioning scheme for checking of runtime images (#78)
- Move Version Check UI to runtime Middleware (#81)
- Remove FAB dependency (#82)

Releasing 3.0.0
